### ISSUE TITLE
ELTP Awards

### ISSUE THREAD

**Issue by anom** [arfie/eltp-draft-packet#6]
Put ELTP awards in stats?

If so it may make sense to rename the section to "Achievements" or "Feats" for short.

A spreadsheet would be required to source data from, and this would allow non-tech people to maintain it. I'm unaware that one currently exists.

Thoughts?

**Comment by arfie** [comment]
My plan was to add xLTP stats to the stats tab as well. Awards is also a good idea!

The best way to go about this is probably to read out the old stats/awards spreadsheets, and either manually or automatically convert them to some JSON format. Since this is probably a lot of work it won't be a priority for me, but if you want to give it a go feel free!
